# Generated by Django 3.1.1 on 2024-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beurlaubung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beurlaubung',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
