# Generated by Django 3.1.1 on 2024-05-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beurlaubung', '0002_auto_20240509_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beurlaubung',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
